# Generated by Django 5.0 on 2025-10-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_user_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Home', 'Home'), ('Away', 'Away'), ('Third', 'Third'), ('CONMEBOL', 'CONMEBOL'), ('UEFA', 'UEFA'), ('CONCACAF', 'CONCACAF'), ('CAF', 'CAF'), ('AFC', 'AFC'), ('OFC', 'OFC'), ('Accessory', 'Accessory')], default='Home', max_length=20),
        ),
    ]
