# Generated by Django 5.0 on 2025-10-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='confederation',
            field=models.CharField(blank=True, choices=[('CONMEBOL', 'CONMEBOL'), ('UEFA', 'UEFA'), ('CONCACAF', 'CONCACAF'), ('CAF', 'CAF'), ('AFC', 'AFC'), ('OFC', 'OFC')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Home', 'Home'), ('Away', 'Away'), ('Third', 'Third'), ('Accessory', 'Accessory')], default='Home', max_length=20),
        ),
    ]
